name: Pull Request on Branch Push
on:
  push:
    branches-ignore:
      - staging
      - main
jobs:
  auto-pull-request:
    name: PullRequestAction
    runs-on: ubuntu-latest
    steps:
      - name: pull-request-staging
        uses: vsoch/pull-request-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: "release/"
          PULL_REQUEST_BRANCH: "staging"
          PULL_REQUEST_TITLE: "(staging) ${{ github.head_ref || github.ref_name }}"
      - name: pull-request-main
        uses: vsoch/pull-request-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: "release/"
          PULL_REQUEST_BRANCH: "main"
          PULL_REQUEST_TITLE: "(production) ${{ github.head_ref || github.ref_name }}"
